title: Selections From Recent 30 Day Map Challenges # 
logo: 
description: > # your text below (remove <br> elements if you don't need line breaks)
  vicky johnson-dahl<br>
  cartographer, dc
  <br>  
  <br>
   <a href="mailto:victoria.johnson@gmail.com?subject=maps!!!">email</a> 
  <br>
  <br>
  (<a href="https://github.com/tjukanovt/30DayMapChallenge">more about the map challenge</a>)
  
  
theme: jekyll-theme-dinky
google_analytics: G-P6Y7G0TC54 # your Google Analytics tracking ID here
